name:                beat-scraper-v3
version:             0.1.0.0
github:              "y2bd/beat-scraper-v3"
license:             BSD3
author:              "Jason Lo"
maintainer:          "github@jasonlo.email"
copyright:           "2019 Jason Lo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/y2bd/beat-scraper-v3#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel
- text

library:
  source-dirs: src

executables:
  beat-scraper-v3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beat-scraper-v3

tests:
  beat-scraper-v3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beat-scraper-v3
